"""updated tables

Revision ID: 2fab7474ff0c
Revises: f33a7452cbc0
Create Date: 2025-12-11 20:08:50.324801

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2fab7474ff0c'
down_revision: Union[str, Sequence[str], None] = 'f33a7452cbc0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_collaborators',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'user_id', name='unique_document_user')
    )
    op.create_index(op.f('ix_document_collaborators_id'), 'document_collaborators', ['id'], unique=False)
    op.add_column('documents', sa.Column('content_type', sa.String(length=20), nullable=True))
    op.add_column('documents', sa.Column('content_blocks', sa.JSON(), nullable=True))
    op.add_column('documents', sa.Column('styles', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'styles')
    op.drop_column('documents', 'content_blocks')
    op.drop_column('documents', 'content_type')
    op.drop_index(op.f('ix_document_collaborators_id'), table_name='document_collaborators')
    op.drop_table('document_collaborators')
    # ### end Alembic commands ###
