"""Added role model

Revision ID: 784c3418a7ae
Revises: 550e0cc10f78
Create Date: 2025-07-18 15:24:51.205574

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '784c3418a7ae'
down_revision: Union[str, Sequence[str], None] = '550e0cc10f78'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('permissions', sa.JSON(), nullable=True))
    op.alter_column('roles', 'workspace_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('roles', 'workspace_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('roles', 'permissions')
    # ### end Alembic commands ###
