"""Add role FK to memberships

Revision ID: ffd45e8b86c7
Revises: 784c3418a7ae
Create Date: 2025-07-18 15:54:17.824278

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ffd45e8b86c7'
down_revision: Union[str, Sequence[str], None] = '784c3418a7ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('memberships', sa.Column('role_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'memberships', 'roles', ['role_id'], ['id'])
    op.drop_column('memberships', 'role')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('memberships', sa.Column('role', postgresql.ENUM('OWNER', 'ADMIN', 'MEMBER', 'VIEWER', name='roleenum'), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'memberships', type_='foreignkey')
    op.drop_column('memberships', 'role_id')
    # ### end Alembic commands ###
